# Generated by Django 5.0.1 on 2024-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0002_programmer_alter_employee_email_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Programmer',
            new_name='programmers',
        ),
    ]
